<a href="https://colab.research.google.com/github/Manuel769/curso_python/blob/main/Sesi%C3%B3n03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
x=20
y=5
#condicional con suma
if x==4 and y<2:
  y=5
else:
  y=2

Suma= x + y
print(Suma)

6

In [18]:
x=4
y=8
#condicional con resta
if x==4 or y<2:
  y=5
else:
  y=2

resta= x - y
print(resta)

9

In [25]:
x=6
y=8
#condicional con producto
#if,elif,else
if x==4:
  y=5
elif x==6:
  y=9
elif x==8:
  y=3
else:
  y=2

producto= x*y
print(producto)
print(y)
print(x)

54
9
6

In [24]:
if x<y:
  print("x es menor que y")
else:
  print("y es menor que x")

x es menor que y

In [8]:
#for
lista = [34,20,3]
suma = 0
for x in lista:
  suma = suma + x
  print("La iteración de la suma es", suma)

print("La suma total es: ",suma)

La iteración de la suma es 34
La iteración de la suma es 54
La iteración de la suma es 57
La suma total es:  114

In [ ]:
lista = [34,20,3,123,567,35,96,19]
suma = 0
for index,x in lista:
  print("La iteración de la suma es",x)

In [11]:
x=0
y=3
while x<y:
  print(x)
  x+=1

  print("Nuevo valor de x: ",x)

0
Nuevo valor de x:  1
1
Nuevo valor de x:  2
2
Nuevo valor de x:  3

In [12]:
#while
x=0
y=150
while x<y:
  print(x)
  x+=1
  if x==50:
    break
  else:
    print("Nuevo valor de x: ",x)

0
Nuevo valor de x:  1
1
Nuevo valor de x:  2
2
Nuevo valor de x:  3
3
Nuevo valor de x:  4
4
Nuevo valor de x:  5
5
Nuevo valor de x:  6
6
Nuevo valor de x:  7
7
Nuevo valor de x:  8
8
Nuevo valor de x:  9
9
Nuevo valor de x:  10
10
Nuevo valor de x:  11
11
Nuevo valor de x:  12
12
Nuevo valor de x:  13
13
Nuevo valor de x:  14
14
Nuevo valor de x:  15
15
Nuevo valor de x:  16
16
Nuevo valor de x:  17
17
Nuevo valor de x:  18
18
Nuevo valor de x:  19
19
Nuevo valor de x:  20
20
Nuevo valor de x:  21
21
Nuevo valor de x:  22
22
Nuevo valor de x:  23
23
Nuevo valor de x:  24
24
Nuevo valor de x:  25
25
Nuevo valor de x:  26
26
Nuevo valor de x:  27
27
Nuevo valor de x:  28
28
Nuevo valor de x:  29
29
Nuevo valor de x:  30
30
Nuevo valor de x:  31
31
Nuevo valor de x:  32
32
Nuevo valor de x:  33
33
Nuevo valor de x:  34
34
Nuevo valor de x:  35
35
Nuevo valor de x:  36
36
Nuevo valor de x:  37
37
Nuevo valor de x:  38
38
Nuevo valor de x:  39
39
Nuevo valor de x:  40
40
Nuevo valor de x:  41
41
Nuevo valor de x:  42
42
Nuevo valor de x:  43
43
Nuevo valor de x:  44
44
Nuevo valor de x:  45
45
Nuevo valor de x:  46
46
Nuevo valor de x:  47
47
Nuevo valor de x:  48
48
Nuevo valor de x:  49
49

In [18]:
x=0
y=150
while x<y:
  print(x)
  x+=1
  if len(str(x))==3:
    print("Error la cadena excede el valor:",x)
    break
  else:
    print("Nuevo valor de x: ",x)

0
Nuevo valor de x:  1
1
Nuevo valor de x:  2
2
Nuevo valor de x:  3
3
Nuevo valor de x:  4
4
Nuevo valor de x:  5
5
Nuevo valor de x:  6
6
Nuevo valor de x:  7
7
Nuevo valor de x:  8
8
Nuevo valor de x:  9
9
Nuevo valor de x:  10
10
Nuevo valor de x:  11
11
Nuevo valor de x:  12
12
Nuevo valor de x:  13
13
Nuevo valor de x:  14
14
Nuevo valor de x:  15
15
Nuevo valor de x:  16
16
Nuevo valor de x:  17
17
Nuevo valor de x:  18
18
Nuevo valor de x:  19
19
Nuevo valor de x:  20
20
Nuevo valor de x:  21
21
Nuevo valor de x:  22
22
Nuevo valor de x:  23
23
Nuevo valor de x:  24
24
Nuevo valor de x:  25
25
Nuevo valor de x:  26
26
Nuevo valor de x:  27
27
Nuevo valor de x:  28
28
Nuevo valor de x:  29
29
Nuevo valor de x:  30
30
Nuevo valor de x:  31
31
Nuevo valor de x:  32
32
Nuevo valor de x:  33
33
Nuevo valor de x:  34
34
Nuevo valor de x:  35
35
Nuevo valor de x:  36
36
Nuevo valor de x:  37
37
Nuevo valor de x:  38
38
Nuevo valor de x:  39
39
Nuevo valor de x:  40
40
Nuevo valor de x:  41
41
Nuevo valor de x:  42
42
Nuevo valor de x:  43
43
Nuevo valor de x:  44
44
Nuevo valor de x:  45
45
Nuevo valor de x:  46
46
Nuevo valor de x:  47
47
Nuevo valor de x:  48
48
Nuevo valor de x:  49
49
Nuevo valor de x:  50
50
Nuevo valor de x:  51
51
Nuevo valor de x:  52
52
Nuevo valor de x:  53
53
Nuevo valor de x:  54
54
Nuevo valor de x:  55
55
Nuevo valor de x:  56
56
Nuevo valor de x:  57
57
Nuevo valor de x:  58
58
Nuevo valor de x:  59
59
Nuevo valor de x:  60
60
Nuevo valor de x:  61
61
Nuevo valor de x:  62
62
Nuevo valor de x:  63
63
Nuevo valor de x:  64
64
Nuevo valor de x:  65
65
Nuevo valor de x:  66
66
Nuevo valor de x:  67
67
Nuevo valor de x:  68
68
Nuevo valor de x:  69
69
Nuevo valor de x:  70
70
Nuevo valor de x:  71
71
Nuevo valor de x:  72
72
Nuevo valor de x:  73
73
Nuevo valor de x:  74
74
Nuevo valor de x:  75
75
Nuevo valor de x:  76
76
Nuevo valor de x:  77
77
Nuevo valor de x:  78
78
Nuevo valor de x:  79
79
Nuevo valor de x:  80
80
Nuevo valor de x:  81
81
Nuevo valor de x:  82
82
Nuevo valor de x:  83
83
Nuevo valor de x:  84
84
Nuevo valor de x:  85
85
Nuevo valor de x:  86
86
Nuevo valor de x:  87
87
Nuevo valor de x:  88
88
Nuevo valor de x:  89
89
Nuevo valor de x:  90
90
Nuevo valor de x:  91
91
Nuevo valor de x:  92
92
Nuevo valor de x:  93
93
Nuevo valor de x:  94
94
Nuevo valor de x:  95
95
Nuevo valor de x:  96
96
Nuevo valor de x:  97
97
Nuevo valor de x:  98
98
Nuevo valor de x:  99
99
Error la cadena excede el valor: 100

In [19]:
x=0
y=150
while x<y:
  print(x)
  x+=1
  print(type(x))
  cadena_numero = len(str(x))
  print(type(str(x)))
  if len(str(x))==3:
    print("Error la cadena excede el valor:",cadena_numero,x)
    break
  else:
    print("Nuevo valor de x: ",x)

0
<class 'int'>
<class 'str'>
Nuevo valor de x:  1
1
<class 'int'>
<class 'str'>
Nuevo valor de x:  2
2
<class 'int'>
<class 'str'>
Nuevo valor de x:  3
3
<class 'int'>
<class 'str'>
Nuevo valor de x:  4
4
<class 'int'>
<class 'str'>
Nuevo valor de x:  5
5
<class 'int'>
<class 'str'>
Nuevo valor de x:  6
6
<class 'int'>
<class 'str'>
Nuevo valor de x:  7
7
<class 'int'>
<class 'str'>
Nuevo valor de x:  8
8
<class 'int'>
<class 'str'>
Nuevo valor de x:  9
9
<class 'int'>
<class 'str'>
Nuevo valor de x:  10
10
<class 'int'>
<class 'str'>
Nuevo valor de x:  11
11
<class 'int'>
<class 'str'>
Nuevo valor de x:  12
12
<class 'int'>
<class 'str'>
Nuevo valor de x:  13
13
<class 'int'>
<class 'str'>
Nuevo valor de x:  14
14
<class 'int'>
<class 'str'>
Nuevo valor de x:  15
15
<class 'int'>
<class 'str'>
Nuevo valor de x:  16
16
<class 'int'>
<class 'str'>
Nuevo valor de x:  17
17
<class 'int'>
<class 'str'>
Nuevo valor de x:  18
18
<class 'int'>
<class 'str'>
Nuevo valor de x:  19
19
<class 'int'>
<class 'str'>
Nuevo valor de x:  20
20
<class 'int'>
<class 'str'>
Nuevo valor de x:  21
21
<class 'int'>
<class 'str'>
Nuevo valor de x:  22
22
<class 'int'>
<class 'str'>
Nuevo valor de x:  23
23
<class 'int'>
<class 'str'>
Nuevo valor de x:  24
24
<class 'int'>
<class 'str'>
Nuevo valor de x:  25
25
<class 'int'>
<class 'str'>
Nuevo valor de x:  26
26
<class 'int'>
<class 'str'>
Nuevo valor de x:  27
27
<class 'int'>
<class 'str'>
Nuevo valor de x:  28
28
<class 'int'>
<class 'str'>
Nuevo valor de x:  29
29
<class 'int'>
<class 'str'>
Nuevo valor de x:  30
30
<class 'int'>
<class 'str'>
Nuevo valor de x:  31
31
<class 'int'>
<class 'str'>
Nuevo valor de x:  32
32
<class 'int'>
<class 'str'>
Nuevo valor de x:  33
33
<class 'int'>
<class 'str'>
Nuevo valor de x:  34
34
<class 'int'>
<class 'str'>
Nuevo valor de x:  35
35
<class 'int'>
<class 'str'>
Nuevo valor de x:  36
36
<class 'int'>
<class 'str'>
Nuevo valor de x:  37
37
<class 'int'>
<class 'str'>
Nuevo valor de x:  38
38
<class 'int'>
<class 'str'>
Nuevo valor de x:  39
39
<class 'int'>
<class 'str'>
Nuevo valor de x:  40
40
<class 'int'>
<class 'str'>
Nuevo valor de x:  41
41
<class 'int'>
<class 'str'>
Nuevo valor de x:  42
42
<class 'int'>
<class 'str'>
Nuevo valor de x:  43
43
<class 'int'>
<class 'str'>
Nuevo valor de x:  44
44
<class 'int'>
<class 'str'>
Nuevo valor de x:  45
45
<class 'int'>
<class 'str'>
Nuevo valor de x:  46
46
<class 'int'>
<class 'str'>
Nuevo valor de x:  47
47
<class 'int'>
<class 'str'>
Nuevo valor de x:  48
48
<class 'int'>
<class 'str'>
Nuevo valor de x:  49
49
<class 'int'>
<class 'str'>
Nuevo valor de x:  50
50
<class 'int'>
<class 'str'>
Nuevo valor de x:  51
51
<class 'int'>
<class 'str'>
Nuevo valor de x:  52
52
<class 'int'>
<class 'str'>
Nuevo valor de x:  53
53
<class 'int'>
<class 'str'>
Nuevo valor de x:  54
54
<class 'int'>
<class 'str'>
Nuevo valor de x:  55
55
<class 'int'>
<class 'str'>
Nuevo valor de x:  56
56
<class 'int'>
<class 'str'>
Nuevo valor de x:  57
57
<class 'int'>
<class 'str'>
Nuevo valor de x:  58
58
<class 'int'>
<class 'str'>
Nuevo valor de x:  59
59
<class 'int'>
<class 'str'>
Nuevo valor de x:  60
60
<class 'int'>
<class 'str'>
Nuevo valor de x:  61
61
<class 'int'>
<class 'str'>
Nuevo valor de x:  62
62
<class 'int'>
<class 'str'>
Nuevo valor de x:  63
63
<class 'int'>
<class 'str'>
Nuevo valor de x:  64
64
<class 'int'>
<class 'str'>
Nuevo valor de x:  65
65
<class 'int'>
<class 'str'>
Nuevo valor de x:  66
66
<class 'int'>
<class 'str'>
Nuevo valor de x:  67
67
<class 'int'>
<class 'str'>
Nuevo valor de x:  68
68
<class 'int'>
<class 'str'>
Nuevo valor de x:  69
69
<class 'int'>
<class 'str'>
Nuevo valor de x:  70
70
<class 'int'>
<class 'str'>
Nuevo valor de x:  71
71
<class 'int'>
<class 'str'>
Nuevo valor de x:  72
72
<class 'int'>
<class 'str'>
Nuevo valor de x:  73
73
<class 'int'>
<class 'str'>
Nuevo valor de x:  74
74
<class 'int'>
<class 'str'>
Nuevo valor de x:  75
75
<class 'int'>
<class 'str'>
Nuevo valor de x:  76
76
<class 'int'>
<class 'str'>
Nuevo valor de x:  77
77
<class 'int'>
<class 'str'>
Nuevo valor de x:  78
78
<class 'int'>
<class 'str'>
Nuevo valor de x:  79
79
<class 'int'>
<class 'str'>
Nuevo valor de x:  80
80
<class 'int'>
<class 'str'>
Nuevo valor de x:  81
81
<class 'int'>
<class 'str'>
Nuevo valor de x:  82
82
<class 'int'>
<class 'str'>
Nuevo valor de x:  83
83
<class 'int'>
<class 'str'>
Nuevo valor de x:  84
84
<class 'int'>
<class 'str'>
Nuevo valor de x:  85
85
<class 'int'>
<class 'str'>
Nuevo valor de x:  86
86
<class 'int'>
<class 'str'>
Nuevo valor de x:  87
87
<class 'int'>
<class 'str'>
Nuevo valor de x:  88
88
<class 'int'>
<class 'str'>
Nuevo valor de x:  89
89
<class 'int'>
<class 'str'>
Nuevo valor de x:  90
90
<class 'int'>
<class 'str'>
Nuevo valor de x:  91
91
<class 'int'>
<class 'str'>
Nuevo valor de x:  92
92
<class 'int'>
<class 'str'>
Nuevo valor de x:  93
93
<class 'int'>
<class 'str'>
Nuevo valor de x:  94
94
<class 'int'>
<class 'str'>
Nuevo valor de x:  95
95
<class 'int'>
<class 'str'>
Nuevo valor de x:  96
96
<class 'int'>
<class 'str'>
Nuevo valor de x:  97
97
<class 'int'>
<class 'str'>
Nuevo valor de x:  98
98
<class 'int'>
<class 'str'>
Nuevo valor de x:  99
99
<class 'int'>
<class 'str'>
Error la cadena excede el valor: 3 100

In [20]:
#funciones
def obtener_nombre_completo():
  return "Manuel Antonny Castillo Navarro"

nombre_completo = obtener_nombre_completo()
print(nombre_completo)

Manuel Antonny Castillo Navarro

In [28]:
def obtener_nombre_completo_con_parametros(nombres,apellidos):
  return  nombres +" "+ apellidos

nombre="Manuel Antonnny"
apellido="Castillo Navarro"

nombre_completo = obtener_nombre_completo_con_parametros(nombre,apellido)
print(nombre_completo)

Manuel Antonnny Castillo Navarro

In [36]:
def formulario_inscripcion(nombre_completo,pais='Perú'):
    return {
        "nombre_completo":nombre_completo,
        "pais":pais
    }


print(formulario_inscripcion(nombre_completo,'Ecuador'))

{'nombre_completo': 'Manuel Antonnny Castillo Navarro', 'pais': 'Ecuador'}

In [40]:
def resta(a=None, b=None):
  if a == None or b == None:
    raise Exception("Error, no se puede realizar la resta sin las dos variables requeridas")
  return a - b

print(resta(2,5))

def suma(a=None, b=None):
  if a == None or b == None:
    raise Exception("Error, no se puede realizar la sumar sin las dos variables requeridas")
  return a + b

def multiplicacion(a=None, b=None):
  if a == None or b == None:
    raise Exception("Error, no se puede realizar la multiplicar sin las dos variables requeridas")
  return a*b

def operaciones(numero1, numero2):
  operacion_suma= suma(numero1,numero2)
  operacion_resta= resta(numero1,numero2)
  operacion_multiplicacion= multiplicacion(numero1,numero2)
  return operacion_suma , operacion_resta , operacion_multiplicacion

numero=5
numero2=10
resultado_operaciones = operaciones(numero,numero2)

print("La suma de ",numero, "y",numero2,"es:",resultado_operaciones[0])
print("La resta de ",numero, "y",numero2,"es:",resultado_operaciones[1])
print("La multipliacion de ",numero, "y",numero2,"es:",resultado_operaciones[2])

-3
La suma de  5 y 10 es: 15
La resta de  5 y 10 es: -5
La multipliacion de  5 y 10 es: 50